channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - librosa
  - tqdm
  - requests
  - colorama
  - ansiwrap
  - pyyaml
  - jsonlines
  - kaldi
  - sox
  - pynini
  - openfst
  - baumwelch
  - ngram
  - praatio
  - biopython
